export const PAGE_TYPE_SEND = 'PAGE_TYPE_SEND';
export const STORAGE_DATA_SEND = 'STORAGE_DATA_SEND';
export const ALARM_DATA_SEND = 'ALARM_DATA_SEND';
export const BUTTON_STATE_SEND = 'BUTTON_STATE_SEND';
export const MONTH_LIST_SEND = 'MONTH_LIST_SEND';
export const DB_VOCABS_SEND = 'DB_VOCABS_SEND';
