export const PAGE_TYPE_SEND = 'PAGE_TYPE_SEND';
export const STORAGE_DATA_SEND = 'STORAGE_DATA_SEND';
export const ALARM_DATA_SEND = 'ALARM_DATA_SEND';
export const BUTTON_STATE_SEND = 'USER_STATE_SEND';
