branch-defaults:
  master:
    environment: vocab-cuckoo-server
global:
  application_name: vocab-cuckoo-server
  default_ec2_keyname: null
  default_platform: 64bit Amazon Linux 2015.03 v1.4.3 running Ruby 2.2 (Puma)
  default_region: ap-northeast-2
  profile: eb-cli
  sc: git
