branch-defaults:
  master:
    environment: VocabCuckoo-env
global:
  application_name: vocab_cuckoo
  default_ec2_keyname: null
  default_platform: 64bit Amazon Linux 2015.03 v1.4.3 running Ruby 2.2 (Puma)
  default_region: ap-northeast-2
  profile: eb-cli
  sc: git
